# this is the configuration file for moviESC

# db params
redis_host: !!str "localhost"
redis_port: !!str "6379"
redis_db: !!str "0"

# key names / formats
key_opendirs: !!str 'opendirs'    # the set containing all the opendirs that have been crawled
key_toIndex: !!str 'toIndex'  # the set where the movies that still need to be indexed are stored
key_failed: !!str 'failed'    # the set where the unreadable (no size/hash) movies are saved
key_noIMDB: !!str 'noIMDB'    # the set containing the movies for which no IMDB was found
key_imdb: !!str 'imdb:#imdbid#'  # the hash containing all the IMDB metadata we are interested in
key_uris: !!str 'uris:#imdbid#'  # the hash containing all the URIs matching a gived IMDBid
key_hashIMDB: !!str 'h2i:#size#:#hash#'    # cached mappings between bytesize/movhash and IMDB ids
key_genres: !!str 'genre:#genre#'  # the set containing all the IMDBids of movies of a given genre

# folders
path_posters: !!str './posters'

# interactive identification allows user to manually specify
# an IMDB id when a movie cannot be identified automatically
interactive_ident: !!bool 'False'

# logger
logging:
  version: 1
  disable_existing_loggers: True

  root:
    level: !!python/name:logging.NOTSET
    handlers: [console]

  loggers:

    # Logging from my application
    dev:
      level: !!python/name:logging.INFO
      handlers: [console]
      qualname: dev
      propagate: false

    movies:
      level: !!python/name:logging.INFO
      handlers: [stderr]
      qualname: movies
      propagate: false

    # Controlling logging of 3rd party libs
    # ...

  handlers:
#    logfile:
#      class: logging.FileHandler
#      filename: moviESC.log
#      formatter: simpleFormatter
#      level: !!python/name:logging.NOTSET

    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET

    stderr:
      class: logging.StreamHandler
      stream: ext://sys.stderr
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET

  formatters:
    simpleFormatter:
      #format: '%(name)s %(asctime)s %(levelname)s %(message)s'
      format: '[%(levelname)s] %(message)s'
      datefmt: '%Y%m%d%H%M%S'
