# this is the configuration file for moviESC

# db params
redis_host: !!str "localhost"
redis_port: !!str "6379"
redis_db: !!str "0"

# key names / formats     
key_toIndex: !!str 'toIndex'  # the queue (actually a set now) where the movies that still need to be indexed are stored
key_failed: !!str 'failed'    # the set where the unreadable (no size/hash) movies are saved 
key_noIMDB: !!str 'noIMDB'    # the set containing the movies for which no IMDB was found

# interactive identification allows user to manually specify
# an IMDB id when a movie cannot be identified automatically 
interactive_ident: !!bool 'False'

# logger
logging:
  version: 1
  disable_existing_loggers: true

  root:
    level: !!python/name:logging.NOTSET
    handlers: [console]

  loggers:

    # Logging from my application
    dev:
      level: !!python/name:logging.INFO
      handlers: [console]
      qualname: dev
      propagate: false

    movies:
      level: !!python/name:logging.INFO
      handlers: [stderr]
      qualname: movies
      propagate: false

    # Controlling logging of 3rd party libs
    # ...

  handlers:
#    logfile:
#      class: logging.FileHandler
#      filename: moviESC.log
#      formatter: simpleFormatter
#      level: !!python/name:logging.NOTSET

    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
    
    stderr:
      class: logging.StreamHandler
      stream: ext://sys.stderr
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET

  formatters:
    simpleFormatter:
      class: !!python/name:logging.Formatter
      #format: '%(name)s %(asctime)s %(levelname)s %(message)s'
      format: '[%(levelname)s] %(message)s'
      datefmt: '%Y%m%d%H%M%S'

